# настройки приложения
spring:
  application:
    name: order-orchestrator
  datasource:
    url: ${SPRING_DATASOURCE_URL:not-set}
    username: ${SPRING_DATASOURCE_USERNAME:not-set}
    password: ${SPRING_DATASOURCE_PASSWORD:not-set}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  docker:
    compose:
      file: ./order-orchestrator/docker-compose.dev.yaml
      lifecycle-management: start-and-stop   # поднимает при старте, останавливает при завершении
      start:
        command: up                         # использовать `docker compose up`
        arguments: --force-recreate         # ВСЕГДА пересоздавать контейнеры
      stop:
        command: down                     # полностью закрывает контейнеры
        arguments: -v

# настройки Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui

# настройки хостов
hosts:
  base-url:
    payment-stub: http://payment-stub:8081/payment
    warehouse-stub: http://payment-stub:8081/warehouse

# настройки поллера
payment-task:
  poller:
    poll-interval: ${TASK_EXEC_POLL_INTERVAL:3s}
    batch-size: ${TASK_EXEC_BATCH_SIZE:5}
    retry-delay: ${TASK_EXEC_RETRY_DELAY:30s}
    max-attempts: ${TASK_EXEC_MAX_ATTEMPTS:10}